FROM jupyter/minimal-notebook

ENV  NBUSER jovyan

WORKDIR /home/$NBUSER/work

# Install bash_kernel:
COPY  requirements.minimal-notebook .
RUN   pip install -r requirements.minimal-notebook

# Copy in an example bash notebook:
COPY  Tutorial_Bash_Arrays.ipynb .
