FROM jupyter/minimal-notebook

ENV  NBUSER jovyan

WORKDIR /home/$NBUSER/work

# Install bash_kernel:
COPY  requirements.minimal-notebook requirements.minimal-notebook 
RUN   pip install -r requirements.minimal-notebook

